# This is a basic workflow to help you get started with Actions

name: Gitee Pages Mirror Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "yixuan-wang.github.io"
        replace: "yixuan-wang.gitee.io"

    - name: Commit to Gitee Branch
      run: |
        git status
        # git checkout gitee
        # git add .
        # git commit "build(mirror): "`date +%Y%m%dT%H%M%S`
        
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:Yixuan-Wang/blog.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:yixuan-wang/blog.git"

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: yixuan-wang
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: yixuan-wang/blog
          branch: gitee
